import os
import os.path
import yaml
import subprocess

def write_camera_assignment(yaml_dict):
    """
    Write camera assignment to mct configuration directory
    """
    # Write yaml file to 'camera_assignment.yaml' in cameras section of mct configuration
    config_dir = os.environ['MCT_CONFIG']
    filename = os.path.join(config_dir, 'cameras', 'camera_assignment.yaml')
    with open(filename,'w') as f:
        f.write('\n# Autogenerated configuration file - do not hand edit\n\n')
        camera_name_list = yaml_dict.keys()
        camera_name_list.sort
        yaml.dump(yaml_dict,f,default_flow_style=False)

def read_camera_assignment():
    """
    Reads the current camera assignment from the camera assignment yaml file. If 
    this file doesn't exist then None is returned.
    """
    config_dir = os.environ['MCT_CONFIG']
    filename = os.path.join(config_dir, 'cameras', 'camera_assignment.yaml')
    if os.path.isfile(filename):
        try:
            with open(filename) as f:
                yaml_dict = yaml.load(f)
        except:
            return None
        return yaml_dict
    else:
        return None

def write_camera_calibration(camera_name, cal_ost_str):
    """
    Writes the camera calibration given the camera name and calibration ost
    string produced by the cameracalibrator node.
    """
    config_dir = os.environ['MCT_CONFIG']
    calibration_dir = os.path.join(config_dir,'calibration')
    if not os.path.isdir(calibration_dir):
        os.mkdir(calibration_dir)
    basename = os.path.join(config_dir,'calibration', camera_name)
    filename_ost = '{0}.ini'.format(basename)
    filename_yaml = '{0}.yaml'.format(basename)
    with open(filename_ost,'w') as f:
        f.write(cal_ost_str)
    subprocess.call(['rosrun', 'camera_calibration_parsers', 'convert', filename_ost, filename_yaml])
    os.remove(filename_ost)


