#!/usr/bin/env python
import roslib
roslib.load_manifest('mct_camera_tools')
import rospy
import os
import os.path
import tempfile

class Camera_Inspector_Master(object):
    """
    Launches camera inspector nodes on all computers in the machine file.
    """
    def __init__(self):
        # Get location of machine file
        self.mct_config = os.path.join(os.environ['ROS_LOCAL'], os.environ['MCT_CONFIG'])
        self.machine_file = os.path.join(self.mct_config, 'machine', 'mct.machine')

        # Get name for autogenerated inspector launch file
        tmp_dir = tempfile.gettempdir()
        file_path, file_name = os.path.split(__file__)
        template_dir = os.path.join(file_path, 'templates')
        self.launch_template = os.path.join(template_dir,'inspector_nodes_launch.xml')
        self.launch_file = os.path.join(tmp_dir,'inspector_nodes.launch')
        self.launch_pid = None
        rospy.init_node('camera_inspector_master')
        self.launch_inspector_nodes()

    def run(self):
        rospy.spin()

    def create_launch_file(self):
        pass

    def delete_launch_file(self):
        pass

    def launch_inspector_nodes(self):
        pass

    def kill_inspector_nodes(self):
        pass

    def clean_up(self):
        pass

# -----------------------------------------------------------------------------
if __name__ == '__main__':

    node = Camera_Inspector_Master()
    node.run()
